# Generated by Django 5.2.12 on 2026-04-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_pushsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("rank_change", "Rank Change"),
                    ("pick_result", "Pick Result"),
                    ("custom", "Custom"),
                ],
                max_length=30,
            ),
        ),
    ]
