# Generated by Django 5.2.12 on 2026-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="tournament_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CricAPI tournament/series ID (replaces CRIC_TOURNAMENT_ID env var).",
                max_length=100,
            ),
        ),
    ]
