# Generated by Django 5.2.12 on 2026-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_bet_window_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="api_paused",
            field=models.BooleanField(
                default=False,
                help_text="Pause all CricAPI calls (live score polling + schedule fetch). Use when API has issues.",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="pick_window_days",
            field=models.PositiveSmallIntegerField(
                default=5, help_text="How many days before a match opens for picks."
            ),
        ),
    ]
