# Generated by Django 5.2.12 on 2026-06-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_split_api_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="odds_sync_paused",
            field=models.BooleanField(
                default=False,
                help_text="Pause automatic odds sync from The Odds API (runs every 6 hours).",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="cricket_api_paused",
            field=models.BooleanField(
                default=False,
                help_text="Pause all CricAPI calls (live score polling + schedule fetch).",
            ),
        ),
    ]
