# Generated by Django 5.2.12 on 2026-03-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0006_alter_match_description_alter_match_tournament_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taken_at", models.DateTimeField(auto_now_add=True)),
                ("rankings", models.JSONField()),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_snapshot",
                        to="teams.match",
                    ),
                ),
            ],
            options={
                "ordering": ["match__datetime"],
            },
        ),
    ]
