# Generated by Django 5.1.7 on 2026-03-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210406_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='tournaments',
            new_name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.CharField(blank='True', max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='match',
            name='match_points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='selection',
            name='fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selection',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selection',
            name='no_negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank='True', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('NR', 'No Results'), ('team1', 'Team1'), ('team2', 'Team2'), ('IP', 'In Progress'), ('TBD', 'TBD'), ('TOSS', 'Toss'), ('DLD', 'Delayed')], default='TBD', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
