# Generated by Django 3.1.7 on 2021-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='Description',
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='team',
            name='tournaments',
            field=models.TextField(default='IPL'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank='True', upload_to=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
