# Generated by Django 3.1.7 on 2021-04-07 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_auto_20210406_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank='True', null='True')),
                ('venue', models.CharField(blank='True', max_length=40, null='True')),
                ('result', models.CharField(choices=[('NR', 'No Results'), ('team1', 'Team1'), ('team2', 'Team2'), ('IP', 'In Progress'), ('TBD', 'TBD')], max_length=10)),
                ('datetime', models.DateTimeField()),
                ('tournaments', models.CharField(blank='True', default='IPL', max_length=50, null='True')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournaments',
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.CharField(blank='True', max_length=40, null='True'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank='True', null='True', upload_to=''),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='teams.match')),
                ('selection', models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('user', models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='team1', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.SET_NULL, related_name='team2', to='teams.team'),
        ),
    ]
