# Generated by Django 5.1.7 on 2026-03-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_model_improvements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.CharField(blank=True, default="IPL", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="venue",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="selection",
            name="selection",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="teams.team"
            ),
        ),
    ]
