# Generated by Django 5.2.12 on 2026-03-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0008_fix_timestamp_column_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="scores",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="match",
            name="status_text",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
