# Generated by Django 5.2.12 on 2026-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_match_scores_match_status_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="playoff",
            field=models.BooleanField(default=False),
        ),
    ]
