# Generated by Django 5.2.12 on 2026-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0014_selection_fake_decoy"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="minute",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
