# Generated by Django 5.2.12 on 2026-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_match_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ranking",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
